import Process from "sys/process"
import Array from "array"

print("content-type: text/plain\n")

// This will print all the Wagi env variable
print("==== Environment: ====")
match (Process.env()) {
  Err(err) => throw err,
  Ok(env) => Array.forEach(print, env),
}

// This will print the route path followed by each query
// param. So /foo?bar=baz will be ["/foo", "bar=baz"].
print("==== Args: ====")
match (Process.argv()) {
  Err(err) => throw err,
  Ok(env) => Array.forEach(print, env),
}
